## library() calls go here
library(conflicted)
library(dotenv)
library(targets)
library(tarchetypes)
library(rmarkdown)
library(readxl)
library(tidyverse)
library(reactable)
library(lubridate)
library(here)
library(tarchetypes)
library(jagstargets)
library(stats)
library(rethinking)
library(posterior)
library(tidyselect)
library(purrr)
library(workflowr)
library(loo)
library(ggthemes)
library(jagsUI)
library(rjags)
library(ggridges)
library(ggthemes)
library(ggdag)
library(RColorBrewer)
library(patchwork)
library(viridis)
library(plotly)
library(knitr)
library(fnmate)
library(kableExtra)
library(pak)

## Conflicted setup
conflicted::conflict_prefer("filter", "dplyr")
conflicted::conflict_prefer("map", "purrr")
conflicted::conflict_prefer("var", "posterior")

 