---
title: "Forecasts model comparison"
output: html_document
date: "2022-09-28"
---

```{r setup, include=FALSE}

knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file())

knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)


options(tidyverse.quiet = TRUE)

knitr::opts_chunk$set(fig.width=11, fig.height=7) 


```


```{r message=FALSE, warning=FALSE, include=FALSE}

renv::activate()

source("./packages.R")

```

# América

```{r}

tar_read(plots_lastweek_forecast_allmodels_2017)$per_loc_density[[1]]
```

# Diego de Alvear

```{r}

tar_read(plots_lastweek_forecast_allmodels_2017)$per_loc_density[[2]] %>% ggplotly
```

# La Francia

```{r}

tar_read(plots_lastweek_forecast_allmodels_2017)$per_loc_density[[3]] %>% ggplotly
```

# Leones

```{r}

tar_read(plots_lastweek_forecast_allmodels_2017)$per_loc_density[[4]] %>% ggplotly
```

# Necochea

```{r}

tar_read(plots_lastweek_forecast_allmodels_2017)$per_loc_density[[5]] %>% ggplotly
```

# Pehuajo

```{r}

tar_read(plots_lastweek_forecast_allmodels_2017)$per_loc_density[[6]] %>% ggplotly
```

# San Vicente

```{r}

tar_read(plots_lastweek_forecast_allmodels_2017)$per_loc_density[[7]] %>% ggplotly
```

# Zavalla

```{r}

tar_read(plots_lastweek_forecast_allmodels_2017)$per_loc_density[[8]] %>% ggplotly
```
